// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPHjVQnd8svCxCglN3v0OZOlmmqk1Lnk',
    appId: '1:386305631015:web:a2361329d0e4d7288d7f02',
    messagingSenderId: '386305631015',
    projectId: 'nvls-29fdd',
    authDomain: 'nvls-29fdd.firebaseapp.com',
    storageBucket: 'nvls-29fdd.firebasestorage.app',
    measurementId: 'G-LDJ8WMYSG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEPIEAkfgks924P2Snmtwq-tbpmljzzU',
    appId: '1:386305631015:android:ecc135408b50d59a8d7f02',
    messagingSenderId: '386305631015',
    projectId: 'nvls-29fdd',
    storageBucket: 'nvls-29fdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1HN66IIiQLgdJKm9XrGikSC5ZUC0TnD4',
    appId: '1:386305631015:ios:7f5c39b537194db08d7f02',
    messagingSenderId: '386305631015',
    projectId: 'nvls-29fdd',
    storageBucket: 'nvls-29fdd.firebasestorage.app',
    iosBundleId: 'com.example.towntalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1HN66IIiQLgdJKm9XrGikSC5ZUC0TnD4',
    appId: '1:386305631015:ios:7f5c39b537194db08d7f02',
    messagingSenderId: '386305631015',
    projectId: 'nvls-29fdd',
    storageBucket: 'nvls-29fdd.firebasestorage.app',
    iosBundleId: 'com.example.towntalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyPHjVQnd8svCxCglN3v0OZOlmmqk1Lnk',
    appId: '1:386305631015:web:6252916c65ad26458d7f02',
    messagingSenderId: '386305631015',
    projectId: 'nvls-29fdd',
    authDomain: 'nvls-29fdd.firebaseapp.com',
    storageBucket: 'nvls-29fdd.firebasestorage.app',
    measurementId: 'G-X0SB7GPLEB',
  );

}